SPADE = '♠'
HEART = '♥'
DIAMOND = '♦'
CLUB = '♣'

PLAYER_SYMBOLS = [SPADE, HEART, DIAMOND, CLUB]

SYMBOL_COLOR_MAPPING = {
    SPADE: 'WHITE',
    HEART: 'BLACK',
    DIAMOND: 'WHITE',
    CLUB: 'BLACK',
}
