version: '3'
services:
    teamchess_db:
        image: postgres:14-alpine
        container_name: teamchess_db
        volumes:
            - primary_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=teamchess
            - POSTGRES_USER=team
            - POSTGRES_PASSWORD=chess
        restart: always
        ports:
            - "15432:5432"
        expose:
            - 15432

    teamchess_app:
        container_name: teamchess_app
        build:
            dockerfile: ./docker/Dockerfile
        env_file:
            - .env
        command: python ./manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - teamchess_db
            - teamchess_redis
        expose:
            - 8000
    teamchess_redis:
        image: bitnami/redis:latest
        container_name: teamchess_redis
        restart: always
        volumes:
            - primary_redis_data:/root/redis
            - primary_redis_conf:/usr/local/etc/redis/redis.conf
        ports:
            - "16379:6379"
        environment:
            - REDIS_PASSWORD=password
            - REDIS_PORT=6379
            - REDIS_DATABASES=1
        expose:
            - 16379


volumes:
    primary_postgres_data:
    primary_redis_data:
    primary_redis_conf:

