# Generated by Django 4.2 on 2024-07-27 13:31

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_game', 'In Game'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=100, null=True))),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
