# Generated by Django 4.2 on 2024-05-13 17:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=100, null=True)),
        ),
    ]
