# Generated by Django 4.2 on 2024-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channel_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
