# Generated by Django 4.2 on 2024-08-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_symbol',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
